{% set version = "5.0.3" %}
{% set name = "fplll" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/fplll/fplll/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: d2b11b7dcb26c30ac1aab9ff75aca9b3dd6e0b0b40c382af16017a717dfe05c2
  patches:
    # Fix for https://github.com/fplll/fplll/issues/205
    # Backported from https://github.com/fplll/fplll/commit/f372182bbe0f0597e7d6e39f8d23f18a21d1d500
    - enumeration-link-error.patch

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - libtool
    - m4
    - gmp
    - mpfr
  run:
    - gmp
    - mpfr

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: https://github.com/fplll/fplll
  license: LGPL v2+
  license_file: {{ SRC_DIR }}/COPYING
  summary: Lattice algorithms using floating-point arithmetic
  doc_url: https://fplll.github.io/fplll
  dev_url: https://github.com/fplll/fplll

extra:
  recipe-maintainers:
    - isuruf
