{% set version = "5.4.4" %}
{% set name = "fplll" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/fplll/fplll/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0fd9d378f04ff886d8864728baf5d90b8b0b82c1e541e92550644fb54f75691d

build:
  number: 0
  skip: true  # [win]
  run_exports:
    # fplll had a breaking change in the 5.2.0 to 5.2.1 upgrade, so it's best to be strict about pinning.
    - {{ pin_subpackage('fplll', max_pin='x.x.x') }}

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('cxx') }}
    - libtool
    - m4
    - make
  host:
    - gmp
    - mpfr
    - qd 2.3.*

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: https://github.com/fplll/fplll
  license: LGPL-2.1-or-later
  license_file: {{ SRC_DIR }}/COPYING
  summary: Lattice algorithms using floating-point arithmetic
  doc_url: https://fplll.github.io/fplll
  dev_url: https://github.com/fplll/fplll

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
